# Generated by Django 4.2.16 on 2024-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anchor',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
